added route and 404
ravijyoti3/rogan-ui-challenge pull request #7
Opened 2023-05-14 06:17 UTC by LokeshKumar-Dev

- [x] Added 404 not found page
- [x] Added All and default route logic

2023-05-16 14:08 UTC, ravijyoti3 requested changes
@LokeshKumar-Dev  Please make the changes suggested

2023-05-16 14:08 UTC, ravijyoti3 commented on src/App.css
> +}
@LokeshKumar-Dev please use tailwind css for any styling.

2023-05-16 14:08 UTC, ravijyoti3 commented on src/App.js
> +            minHeight: 280,
@LokeshKumar-Dev Use tailwind css only.

2023-05-16 14:08 UTC, ravijyoti3 commented on src/Components/Article/SideBar.jsx
> +          }}
@LokeshKumar-Dev

2023-05-16 14:08 UTC, ravijyoti3 commented on src/Components/Article/index.jsx
> +  );
@LokeshKumar-Dev These fragments are useles, you can directly use `<ArticleSection/>`
```suggestion
  return (
      <ArticleSection />
  );
```

2023-05-16 18:41 UTC, LokeshKumar-Dev commented
All Done!!!
[https://www.loom.com/share/75bbe54f1a0e4fe888e3830e69571a0d](url)

2023-05-24 05:37 UTC, ravijyoti3 commented
Always create pull request to your own repo

@LokeshKumar-Dev

2023-05-24 11:50 UTC, closed without merging